branches:
  only:
    - master

language: node_js

node_js:
  - "10.0"

script:
  - npm install
  - npm run build
  - npm run test --if-present

install:
  - npm install -g firebase-tools

after_success:
  deploy:
    provider: firebase
    token:
      secure: $FIREBASE_TOKEN
  project: "filipg-test-server"
