branches:
  only:
    - react-app

language: node_js

node_js:
  - "10.16.0"

script:
  - npm install
  - npm run build
  - npm run test --if-present
  - cd functions
  - npm install

install:
  - npm install -g firebase-tools

after_success:
  - firebase deploy --project filipg-test-server --token $FIREBASE_TOKEN